version: '3.8'

services:
  frontend-dev:
    image: node:18-alpine
    container_name: vue-dev
    working_dir: /app
    volumes:
      - type: bind
        source: .
        target: /app
      - type: volume
        source: vue-node-modules
        target: /app/node_modules
    ports:
      - '5173:5173'
    command: sh -c "npm install && npm run dev"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - VITE_HOST=0.0.0.0 # ¡Crucial para Docker!
    networks:
      - vue-net

  frontend-prod:
    build: .
    ports:
      - '8080:80'
    container_name: vue-prod
    networks:
      - vue-net

networks:
  vue-net:
    driver: bridge

volumes:
  vue-node-modules:
